### ISSUE TITLE
Move telemeter server metrics whitelist to a ConfigMap

### ISSUE THREAD

**Issue by jfchevrette** [openshift/telemeter#121]
https://github.com/openshift/telemeter/blob/ee4a19a2ba06b0c3d6f3bd471d90b7c6318ebfcf/manifests/server/list.yaml#L12

Secrets are ignored in upstream manifests and are instead fetched from a secrets store and applied during CI/CD. Because of this, the whitelist key in the above secret will never be applied to the running telemeter instances when changes are merged to this repo.

The established pattern is that non-secret / volatile data should reside in a ConfigMap which is not ignored by our CI which would allow changes to be merged without the intervention of the SRE team to update/apply a secret.

Would it be posible to move the whitelist to a ConfigMap object?

**Comment by squat** [comment]
closed by #131
