### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by paliwalpriyank** [openshift/telemeter#166]
- I am getting below error while building the project:

priyank@priyank-HP-Pavilion-Laptop-15-cc1xx:~/go/src/telemeter$ make
find: ‘./benchmark’: No such file or directory
go build ./cmd/telemeter-client
cmd/telemeter-client/main.go:21:2: cannot find package "github.com/openshift/telemeter/pkg/forwarder" in any
of:
        /home/priyank/go/src/telemeter/vendor/github.com/openshift/telemeter/pkg/forwarder (vendor tree)
        /usr/local/go/src/github.com/openshift/telemeter/pkg/forwarder (from $GOROOT)
        /home/priyank/go/src/github.com/openshift/telemeter/pkg/forwarder (from $GOPATH)

cmd/telemeter-client/main.go:22:2: cannot find package "github.com/openshift/telemeter/pkg/http" in any of:
        /home/priyank/go/src/telemeter/vendor/github.com/openshift/telemeter/pkg/http (vendor tree)
        /usr/local/go/src/github.com/openshift/telemeter/pkg/http (from $GOROOT)
        /home/priyank/go/src/github.com/openshift/telemeter/pkg/http (from $GOPATH)
cmd/telemeter-client/main.go:23:2: cannot find package "github.com/openshift/telemeter/pkg/metricfamily" in a
ny of:
        /home/priyank/go/src/telemeter/vendor/github.com/openshift/telemeter/pkg/metricfamily (vendor tree)
        /usr/local/go/src/github.com/openshift/telemeter/pkg/metricfamily (from $GOROOT)
        /home/priyank/go/src/github.com/openshift/telemeter/pkg/metricfamily (from $GOPATH)
Makefile:18: recipe for target 'build' failed
make: *** [build] Error 1

- I tried to resolve this by getting this project as vendor dependency using glide, but the latest release available is  3.11.0:

priyank@priyank-HP-Pavilion-Laptop-15-cc1xx:~/go/src/telemeter$ glide get github.com/openshift/telemeter
[WARN]  The name listed in the config file (github.com/openshift/telemeter) does not match the current locati
on (telemeter)
[INFO]  Preparing to install 1 package.
[INFO]  Attempting to get package github.com/openshift/telemeter
[INFO]  --> Gathering release information for github.com/openshift/telemeter
[INFO]  The package github.com/openshift/telemeter appears to have Semantic Version releases (http://semver.o
rg).
[INFO]  The latest release is **v3.11.0**. You are currently not using a release. Would you like
[INFO]  to use this release? Yes (Y) or No (N)
Y

- I continued with 3.11 release but still getting error for metricfamily:

cmd/telemeter-client/main.go:23:2: cannot find package "github.com/openshift/telemeter/pkg/metricfamily" in a
ny of:
        /home/priyank/go/src/telemeter/vendor/github.com/openshift/telemeter/pkg/metricfamily (vendor tree)
        /usr/local/go/src/github.com/openshift/telemeter/pkg/metricfamily (from $GOROOT)
        /home/priyank/go/src/github.com/openshift/telemeter/pkg/metricfamily (from $GOPATH)

Am I doing anything wrong or the build is broken?

**Comment by squat** [comment]
Hi @paliwalpriyank the build is not broken. From the looks of the code you shared, it appears that you have checked the code out into a non-standard location that is not playing well with your local Golang setup. You shared a line that says:
```shell
priyank@priyank-HP-Pavilion-Laptop-15-cc1xx:~/go/src/telemeter$ make
```
This indicates that you have the project checked out to `$GOPATH//src/telemeter`. You should instead put the project in `$GOPATH/src/github.com/openshift/telemeter`. Indeed, you can see that Go was complaining that it could not find the package in that very location:
```shell
...
/home/priyank/go/src/github.com/openshift/telemeter/pkg/forwarder
```

If you are not yet familiar, I suggest looking over the documentation for conventions in writing Go code: https://golang.org/doc/code.html#Workspaces.
