### ISSUE TITLE
Consider sending some human-meaningful cluster name or domain?

### ISSUE THREAD

**Issue by cben** [openshift/telemeter#172]
### Motivation
A user running installer according to try.openshift.com instructions, typed in a cluster "name", say `cben-1-test`.  It affects the cluster domain names, e.g. `console-openshift-console.apps.cben-1-test.sdev.devshift.net`.
However the telemetry data AFAICT is only identified by the long hex id.  If one creates say 5 clusters, they can only appear in https://cloud.redhat.com/openshift/clusters/ named by these hex ids, and to see meaninful names the user has to manually edit the "display name" of each cluster there.  Which requires finding the ids (in `metadata.json` written by installer, or somewhere inside the cluster itself).  

### Proposal
- If some metric included the chosen name / domain, https://cloud.redhat.com/openshift/clusters/ could offer a better experience for self-installed clusters.
  - Full domain would also allow cloud.redhat.com to offer a link to the cluster's console (currently not supported for self-installed clusters, only for clusters installed from the site).

- There might be other ways to improve this from installer side (installer explicitly "phoning home"  instead of relying on telemetry for first registration; installer printing out deep link into https://cloud.redhat.com/ pointing to that cluster).

### Privacy Considerations
This proposes making the collected data **less anonymous**, should be weighed cautiously.  
Note that Red Hat already knows *who* created the cluster (auth token used in telemetry is account-specific), this is just about the name / domain the user chose.

**Comment by squat** [comment]
Hi Beni,
We've discussed some similar ideas before, namely around sending non-metric data through Telemeter. Telemeter is not really designed to handle this use case and, as you said, it in fact makes the data more personally identifying.

The heart of what this proposal aims to do is to do a JOIN on two data sets:
1. Telemetry data; and
2. customer/cluster data.

This JOIN should really be done serverside by the cloud.redhat.com service rather that in the metrics. The service should make a request to Tollbooth using the customer's ID and retrieved cluster ID to determine the cluster metadata and use this data to render the view.

@s-urbaniak any thoughts?

**Comment by cben** [comment]
FYI node hostnames are now visible in telemetry via `up{job="crio"}` and `up{job="kubelet"}` metrics, e.g. 
`up{_id="0b561604-f6a1-4b7c-a23d-e559dc04a008",endpoint="https-metrics",instance="192.168.79.24:10250",job="kubelet",namespace="kube-system",node="master-0.multiarch-ocp-testing.redhat.com",pod="telemeter-server-9",prometheus="openshift-monitoring/k8s",prometheus_replica="prometheus-telemeter-0",service="kubelet"}`

**Comment by squat** [comment]
Setting the question of PII aside, this work is completely doable; it simply requires the party who owns this data to expose a metric that is scraped by the cluster monitoring stack. Once the v2 stack is fully in place, it will be trivial for other components (e.g. installer) to implement the client and send data themselves. See observatorium/up for an example implementation.

**Comment by cben** [comment]
https://docs.openshift.com/container-platform/4.1/telemetry/about-telemetry.html says:

> Telemetry does not collect, and will never collect, identifying information like user names, passwords, or the names or addresses of user resources.

"user resources" is somewhat vague, but reading this one might be surprised that IPs and hostnames are collected.  
Who can settle PII question?  I think it needs a decision one way or the other.

**Comment by squat** [comment]
We should ensure the docs are straightforward about the collected data so that users are not surprised. An up to date  dump of metrics from an actual openshift cluster can always be found in this repo here: https://github.com/openshift/telemeter/blob/master/docs/sample-metrics.md

**Comment by cben** [comment]
I think this can be closed by https://github.com/openshift/console-operator/pull/270 + #239, there is now `console_url` :tada:

We'll create internal tickets to surface this info in cloud.redhat.com/openshift.
