### ISSUE TITLE
Need more information on what is gathered and what is anonymized

### ISSUE THREAD

**Issue by rmahroua** [openshift/telemeter#290]
Hey :) 
I am looking for more information about which data is retrieved/ gather, and what/how it is anonymized.
I could submit a PR to update the documentation if needed.
Thanks,
-razique

**Comment by squat** [comment]
Hi @rmahroua you can find information about all collected metrics in this doc: https://github.com/openshift/telemeter/blob/master/docs/data-collection.md

Also, you can find example metrics collected from a running OpenShift cluster here: https://github.com/openshift/telemeter/blob/master/docs/sample-metrics.md

**Comment by rmahroua** [comment]
Excellent, thanks Lucas, this is super useful.
