### ISSUE TITLE
Metrics are too long to transmit. 

### ISSUE THREAD

**Issue by bpayt2** [openshift/telemeter#342]
I have setup my clusters to use Telemeter Client to federate metrics to a single OCP cluster with Telemeter Server. The Telemeter Client continues to fail and report the following error "error: unable to forward results: the incoming sample data is too long". I have reduced the scope to a single metric {__name__="kube_pod_container_resource_requests_cpu_cores"} in the Telemeter Client configuration; however, it still reports this error. I can get some metrics to work; such as {__name__="up"} and {__name__="cluster_version"} with the same setup. 

Telemeter-Client Cluster: v3.11.200
Telemeter-Server Cluster: 4.3.13

**Comment by squat** [comment]
Hi @bpayt2, the log message you are seeing is the result of response size limiting that the Telemeter client applies to all responses it receives from Prometheus. It is controlled via the `--limit-bytes` flag (https://github.com/openshift/telemeter/blob/master/cmd/telemeter-client/main.go#L58). The flag has a default value of 200kb, meaning that when the client scrapes Prometheus, any HTTP response with a body longer than 200kb will trigger this error.

There is currently no way to disable the limiting, however if you are running your own instance of Telemeter client, then you can certainly set the limit via the flag as arbitrarily high as you like.
