### ISSUE TITLE
Document linked in readme is not accessible

### ISSUE THREAD

**Issue by marhag87** [openshift/telemeter#347]
The document linked under the title `Adding new metrics to send via telemeter` in the readme is not accessible to the public.
Link: https://docs.google.com/document/d/1a6n5iBGM2QaIQRg9Lw4-Npj6QY9--Hpx3XYut-BrUSY/edit?usp=sharing

**Comment by lilic** [comment]
Hey! Thanks for the issue, that is for internal red hat components, adding new telemetry metrics for components outside of Red Hat is not something that is intended to work currently hence the google doc is accessible for red hat folks only. It only contains things around which people to ping for approval of telemetry metrics on our internal slack channel hence why that is in the google document. If other components at some point will be able to add telemetry we will make sure to make instructions different.

Note that the actual allow list for telemetry is public in https://github.com/openshift/cluster-monitoring-operator#adding-new-metrics-to-be-sent-via-telemetry

Hope that answers your question. :)

**Comment by marhag87** [comment]
Could be an idea to put a note on it that it's intended, so people like me don't get confused. Thanks for the answer!
