### ISSUE TITLE
Missing prometheus operator

### ISSUE THREAD

**Issue by jfchevrette** [openshift/telemeter#61]
The manifests [here](https://github.com/openshift/telemeter/blob/27eb47cfd58dd536ae74dd1cad39303249aec8bc/manifests/prometheus/prometheus.yaml) creates a `Prometheus` CR but there is no prometheus-operator in the namespace that can pick it up.

Is there a requirement that prometheus-operator should be deployed prior to this?

Should it be deployed from OLM?

Can we / should we add an OLM subscription manifest in this repo to deploy prometheus-operator?

**Comment by squat** [comment]
My understanding was that we were deploying these manifests to a cluster with OLM already enabled. Is that not the case? We can add a bundle for deploying the PO, however, it seems a little out of scope for this repository.

**Comment by jfchevrette** [comment]
OLM is installed indeed, but my understanding is that in order to get the prometheus-operator installed in our own namespace we'd have to create a Subscription or an InstallPlan? I think it makes sense that this repo has the manifests to create the PO Subscription as it is a hard dependency. Why would we not want to do this?

By doing that it'll enable us to deploy to any OLM enabled cluster w/o needing to apply any extra config to the namespace we deploy to.

**Comment by squat** [comment]
The Telemeter Prometheus does depend on having a Prometheus operator present to operate on the Prometheus and ServiceMonitor objects, however, the Prometheus Operator can be deployed many different ways. I am not sure it makes sense to be prescriptive about how that installation occurs, at least not in the Telemeter repository. It could instead make sense to include these subjective details as part of the configuration needed for bootstrapping and setting up namespaces to which all of the resources are deployed.

I am not totally against the idea, but it seems like including this configuration should be outside of the scope of this repo.

**Comment by jfchevrette** [comment]
@squat Thanks for your input. I think what you said makes a lot of sense. I'll work on the PO deploy manifests outside of this repo.

**Comment by jfchevrette** [comment]
Prometheus operator is now deployed out of band. Closing.
