### ISSUE TITLE
Telemeter server statefulset/pods set to use telemeter-server serviceAccount which doesn't exist

### ISSUE THREAD

**Issue by jfchevrette** [openshift/telemeter#65]
https://github.com/openshift/telemeter/blob/65edaca6a4dc37c65c13fee2fe4e46a4eb4fb8f1/manifests/server/list.yaml#L143

Should we create this SA in the scope of this repo or is it expected that it is created prior to applying the manifests?

**Comment by squat** [comment]
Yes, absolutely! I’ll add it Monday!
