### ISSUE TITLE
Telemeter server logs: [$(NAME)] node joined $(NAME)

### ISSUE THREAD

**Issue by jfchevrette** [openshift/telemeter#68]
On telemeter server startup the following is outputed to the console. 

Unsure where the $(NAME) is coming from but it'd probably useful to see the real data here

```
2018/10/29 13:20:29 Storing metrics on disk at /var/lib/telemeter
2018/10/29 13:20:29 [$(NAME)] node joined $(NAME)
2018/10/29 13:20:29 Starting telemeter-server $(NAME) on 0.0.0.0:8443 (internal=0.0.0.0:8081, cluster=0.0.0.0:8082)
```

**Comment by squat** [comment]
right, this is due to:
https://github.com/openshift/telemeter/blob/master/manifests/server/list.yaml#L88

I can add this as an environment variable from a secret. Or maybe we can use a downward API environment variable to get this automatically. Thoughts, @s-urbaniak

**Comment by s-urbaniak** [comment]
We could leverage the synthesized `metadata.name` and pass it as an env which will include a statefulset identifier. Essentially we had this already in the past:
https://github.com/openshift/telemeter/blob/6835607e8063ea4fb48b6b584770522f5192fff7/deploy/telemeter-server.yaml#L86-L90
