### ISSUE TITLE
Remove volumeClaimTemplates from StatefulSet manifest

### ISSUE THREAD

**Issue by jmelis** [openshift/telemeter#71]
Any attempts to `oc apply` an existing StatefulSet will fail if the new template
contains `volumeClaimTemplates` with the following message:

```
The StatefulSet "telemeter-server" is invalid: spec: Forbidden: updates
to statefulset spec for fields other than 'replicas', 'template', and
'updateStrategy' are forbidden.
```

We believe the underlying problem to be a bug in k8s. In this case, the
generated StatefulSet template contains `volumeClaimTemplates = []`. When the
StatefulSet is created from scratch, that value is removed from the
representation as it's an empty array. However, upon running `oc apply` again
with the same template the validation fails as it believes we're trying to
change the `volumeClaimTemplates` field.

Would it be possible for you to tweak the jsonnet generation so this value is
removed?

**Comment by squat** [comment]
The issue is that Jsonnet forces the StatefulSet constructor to supply a value for the volumeClaimTemplates. The solution is to simply hide that field in Jsonnet. Sur will post a fix.
