### ISSUE TITLE
Avoid of manual updates of template objects for prom telemeter

### ISSUE THREAD

**Issue by riuvshin** [openshift/telemeter#92]
today changes in https://github.com/openshift/telemeter/blob/master/manifests/prometheus/list.yaml is not picked up with CD that we have. So in order to update some objects, we used to do manual updates which is not acceptable for a proper CD set-up.

**Comment by jfchevrette** [comment]
@riuvshin I think the file has evolved since you opened this. Can you verify if this is still a problem and if so can you elaborate on what the issue is exactly? I have deployed using that file via CD today and it worked just fine.
