### ISSUE TITLE
Prometheus should store data to a persistent storage backend

### ISSUE THREAD

**Issue by jfchevrette** [openshift/telemeter#99]
Following our conversation last week, I'm opening this issue to discuss adding persistent storage to Prometheus for telemeter.

I see two options:
- Add a spec.storage.volumeClaimTemplate on the Prometheus object and use EC2 backed PVs to store data.
- Deploy Thanos and use that as a storage backend

I think we can also do both where EC2 would be short term data and Thanos/S3 would have mid-long term data?

We need to keep in mind EC2 PV resizing is not possible at the moment on the target platform so if we're going to use that we'll need to think through sizing the volumes adequately for the amount of data we expect to store.

**Comment by squat** [comment]
If we really want some kind of persistence, I think we should add Thanos to our architecture. This will do automatic backing up (to S3) and compaction of all collected metrics, while still allowing them to be queried.

cc @brancz

**Comment by brancz** [comment]
@squat I think that's a good idea.

**Comment by jfchevrette** [comment]
@brancz @squat what is the status on this?

**Comment by jfchevrette** [comment]
Addressed by #126
